### ISSUE TITLE
Create Beginning Board

### ISSUE THREAD

**Issue by lehmana** [OSU-CS361-W17/group3_project1#1]
This issue is to create the "makeNewModle" function so that it creates a board at the beginning of the game. This board should be in the correct format to be sent to the view. It should have no ships placed for the user. It should have all the ships placed for the computer. It should have no hits, no misses, and should not be a win.

**Comment by Swarles-Barkley** [comment]
(It's Sean)

I'll solve this issue by developping the newModel() function on the provided backend skeleton such that it returns a JSON object which subscribes to the format found on step 3 of the instructions
