### ISSUE TITLE
Get the Model

### ISSUE THREAD

**Issue by lehmana** [OSU-CS361-W17/group3_project1#2]
This issue is to create the "getModelFromReg" function. It should not place ships or hits but should get requests from the user and send them to the appropriate function. The functions it will send to are "fireAt" and "placeShips". It will need to be able to properly communicate with both function, take back their changes to the model, and return it to the view.

**Comment by sharipol** [comment]
(Lazar)
I'll solve this issue by creating a getModelFromReg() function that will take user requests and send them to the proper function in the backend, and then sends the updated the status of the game back to the user.

**Comment by lehmana** [comment]
Assigned to Lazar
