### ISSUE TITLE
Fire Function

### ISSUE THREAD

**Issue by lehmana** [OSU-CS361-W17/group3_project1#3]
This issue is writing the "fireAt" function. This function should receive a model(game board) and the location the user wants to make a hit on the computer board. It should determine if that was a hit or a miss and properly record that. It should then return a proper model back.

**Comment by jahneff** [comment]
I will solve by comparing the coordinated of the shot to the coordinates of each ship. Storing shot coordinates in hit or miss array, depending on result.

**Comment by jahneff** [comment]
Solved 2/3 at 7:15 pm
